from langchain_ollama import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage


llm = ChatOllama(
    model="llama3",
    max_tokens=100
)

# Promopt : is a string that contains the prompt to be sent to the LLM
# Types of Prompts:
# 1. System Prompt: A system prompt is a message that sets the behavior of the model. It can be used to instruct the model on how to respond to user inputs.
# 2. User Prompt: A user prompt is a message that is sent to the model by the user. It can be used to ask questions or provide information to the model.
# 3. AI Prompt: An AI prompt is a message that is generated by the model in response to a user prompt. It can be used to provide information or answer questions.

while True:
    prompt = input("User : ")
    if prompt.lower() == "exit":
        break

    response = llm.invoke(prompt)
    print("Bot : "+response.content)

print("Goodbye!")

